import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Gabarito } from "next/font/google";
import "./styles.css";

const gabarito = Gabarito({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-gabarito",
});

export default function RootLayout({ children }: { children: any }) {
  return (
    <html lang="en">
      <body className={gabarito.variable}>{children}</body>
    </html>
  );
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Joke Generator",
  description: "Generated by AI",
};

/*
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

*/
